### ISSUE TITLE
Typescript dependency?

### ISSUE THREAD

**Issue by mattrossman** [remotion-dev/template-helloworld-javascript#2]
Since this is a javascript template, why is it necessary to install `typescript` and `ts-node` as dependencies?

If I remove them then I can't run `remotion preview`:

```
Error: Cannot find module 'typescript'
```

The docs say the only dependencies for Remotion are FFMPEG and Node.js. Surely there is a way to use Remotion without Typescript?

Overall there is a lot of noise in `package.json` (15 dependencies for a hello world project?)

**Comment by JonnyBurger** [comment]
Hey Matt!

Thanks a lot for the feedback, you are right - we have now removed 5 dependencies that were not necessary. If you want it super bear, `eslint`, `@remotion/eslint-config` `express` (for built-in server) and `prettier` are also not stricly necessary, but I think it's a good default to leave them there and have some functionality out of the box.

Hopefully we address the concerns! And yes, you can totally use Remotion without Typescript.
